image: node:8

stages:
    - pre
    - test
    - publish
    - post

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

variables:
    DOCKER_DRIVER: overlay2

before_script:
    - npm generate-dotenv
    - npm

close:issue:
    image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-close-issue
    stage: pre
    before_script: []
    only:
        - master
    script:
        - apk add --no-cache --upgrade grep
        - ISSUE=$(echo $CI_COMMIT_MESSAGE | grep -oP "(?<=Fixes \#)[0-9]+" || echo '1')
        - gitlab_auto_close_issue --issue $ISSUE --remove-label "Doing" --remove-label "To Do"

create:merge-request:
    image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-mr
    stage: pre
    before_script: []
    except:
        - production
        - master
        - tags
    script:
        - gitlab_auto_mr -t master -c WIP -d .gitlab/merge_request_templates/merge_request.md -r -s --use-issue-name

create:gitlab:release:
    image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-release
    stage: post
    only:
        - /^release/.*$/
    except:
        variables:
        - $CI_COMMIT_TAG =~ /beta/
        - $CI_COMMIT_TAG =~ /alpha/
    before_script: []
    script:
        - gitlab_auto_release -c CHANGELOG.md -d "This was auto-generated by the gitlab-auto-release tool, https://gitlab.com/gitlab-automation-toolkit/gitlab-auto-release." --artifacts "publish:android:package"

