image: node:8

stages:
    - build
    - test
    - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - npm generate-dotenv
  - npm