
image: node:12.18.4

services:
    - docker:dind

stages:
    - build
    - deploy
  
build:
    stage: build
    only:
        - build
    script:
        - npm install
        - docker-compose up -d --build

deploy:
    stage: deploy
    only: 
        - deploy
    script:
        - docker-compose up -d --build
