image: node:8

stages:
    - build
    - deploy

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./node_modules/

install:
    stage: deploy
    tags:
        - docker
    script:
        - npm install

build:ios:
    stage: build
    tags:
        - ios
        - node
        - react-native
    before_script:
        - ./dev-start.sh
    script:
        - ./scripts/build-ios.sh
    artifacts:
        paths:
        - ./build/app.zip
    cache:
        key: ${CI_COMMIT_REF_SLUG}-ios
        paths:
        - ./node_modules/
        - ./ios/Pods/
    
deploy:ios:
    stage: deploy
    dependencies:
        - build:ios
    tags:
        - docker
    image: emiketic/essentials
    variables:
        APPETIZE_PLATFORM: ios
        APPETIZE_ID: $APPETIZE_IOS_ID
    script:
        - ./scripts/deploy.sh ./build/app.zip