image: node:8

image: node:12.18.4

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf build
  - npm install

pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
  artifacts:
    paths:
      - public
  only:
    - master
