
image: node:12.18.4

stages:
    - build
    - deploy
  
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - ./node_modules/
        -.npm/

build:
    stage: build
    script:
        - npm install
        - ./scripts/build.sh
    artifacts:
        paths:
        - ./build/app-.zip
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
        - ./node_modules/
        - ./ios/Pods/

deploy:
    stage: deploy
    dependencies:
        - build
    cache: {}
    image: emiketic/essentials
    script:
        - ./scripts/deploy.sh ./build/app.zip
