image: node:12.18.4

workflow:
    rules:
      - if: '$CI_COMMIT_BRANCH'

stages:
    - build
    - deploy

build:
    image: docker:latest
    stage: build
    services:
      - docker:dind
    script:
        - npm install
        - npm run build
        - rm -rf public
        - mv build public
    artifacts:
        paths:
        - public
    only:
      - master
  
deploy:
    image: docker:latest
    stage: deploy
    services:
        - docker:dind
    script:
        - npm install
        - npm run build
        - rm -rf public
        - mv build public
    artifacts:
        paths:
        - public 
