
image: docker

services:
    - docker:dind

stages:
    - build
    - deploy
  
build:
    stage: build
    script:
        - npm install
        - docker-compose up
    artifacts:
        paths:
            - ./build/app-.zip
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - node_modules/
            - ./ios/Pods/

deploy:
    stage: deploy
    dependencies:
        - build
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - node_modules/
    image: emiketic/essentials
    script:
        - docker-compose up
