image: ruby:2.7

stages:
    - build
    - deploy

build:
    image: docker:latest
    stage: build
    services:
      - docker:dind
    script:
        - gem install bundler
        - bundle install
        - bundle exec jekyll build -d build
    artifacts:
        paths:
        - public
    only:
      - master
  
deploy:
    image: docker:latest
    stage: deploy
    services:
      - docker:dind
    script:
        - gem install bundler
        - bundle install
        - bundle exec jekyll build -d deploy
    artifacts:
        paths:
        - public
    except:
      - master
  