image: node:12.18.4

before_script:
    - npm install hexo-cli -g
    - npm install

stages:
    - build
    - deploy

build:
    image: docker:latest
    stage: build
    services:
      - docker:dind
    before_script:
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
      - docker build --pull -t "$CI_REGISTRY_IMAGE" .
      - docker push "$CI_REGISTRY_IMAGE"
      - hexo deploy 
    artifacts:
        paths:
        - public
    only:
      - master
  
deploy:
    image: docker:latest
    stage: deploy
    services:
      - docker:dind
    before_script:
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
      - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
      - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      - hexo deploy
    artifacts:
        paths:
        - public
    except:
      - master
  